server:
  port: 8901

spring:
  application:
    name: book-service
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: books
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
