server:
  port: 8091

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-add-partitions: true

      bindings:
        bookEventProcessor-out-0:
          destination: create-book
